/**
 * Public Project Blueprint barrel.
 * Safe for client imports — no server-only engine, rates, or margins.
 */

export type {
  ScreenId,
  JourneyStepId,
  ConfidenceLevel,
  ScenarioKind,
  UnknownChoice,
  MoneyRange,
  TimelineRange,
  PublicScenarioResult,
  PhaseBreakdownItem,
  CostDriver,
  PublicConfidence,
  PublicAssumption,
  PublicEstimateResult,
  ProjectBlueprintAnswers,
  ClassifierSuggestion,
  ClassifierSuggestionCategory,
  IdeaClassificationResult,
  ReviewSummary,
  ReviewSummarySection,
  MobileFollowUpAnswers,
  MultiTenantFollowUpAnswers,
  KycFollowUpAnswers,
  ExistingProductFollowUpAnswers,
  LegacyFollowUpAnswers,
  AiFollowUpAnswers,
  CloudFollowUpAnswers,
  PaymentsFollowUpAnswers,
  RegulatedFollowUpAnswers,
  IntegrationDetailAnswers,
  DeadlineConflictResolution,
} from "./types";

export {
  projectBlueprintAnswersSchema,
  normalizeAnswers,
  isAnswerUnknown,
  type ProjectBlueprintAnswersInput,
  type ProjectBlueprintAnswersParsed,
} from "./answers";

export {
  QUESTION_CATALOGUE,
  CATALOGUE_SCREENS,
  CATALOGUE_QUESTIONS,
  CATALOGUE_FOLLOW_UPS,
  DEFAULT_UNKNOWN_OPTIONS,
  UNSURE_ONLY,
  ADVICE_OPTIONS,
  getScreen,
  getQuestion,
  getQuestionsForScreen,
  getVisibleFollowUps,
  getReviewScreenMeta,
  type QuestionCatalogue,
  type QuestionDefinition,
  type FollowUpDefinition,
  type ScreenDefinition,
  type QuestionOption,
  type QuestionInputType,
  type UnknownOptionConfig,
} from "./questions";

export {
  PRIMARY_STEP_ORDER,
  getVisibleSteps,
  getNextStep,
  getPreviousStep,
  canProceed,
  getStepProgress,
  getActiveFollowUpIds,
  getCatalogueVersion,
  type JourneyStep,
  type ProceedResult,
  isWebsiteRoute,
  isCustomSoftwareRoute,
  needsMobileFollowUps,
  needsPaymentsFollowUps,
  needsMultiTenantFollowUps,
  needsKycFollowUps,
  needsExistingProductFollowUps,
  needsLegacyFollowUps,
  needsAiFollowUps,
  needsCloudFollowUps,
  needsIntegrationDetails,
  needsMigrationFollowUps,
  needsRegulatedFollowUps,
  needsDeadlineConflictFollowUps,
  hasDeadlineConflict,
  shouldRecommendDiscovery,
  countSignificantUnknowns,
  isScreenVisible,
  CAPABILITY_DEPENDENCIES,
  FOUNDATION_IDS,
  resolveCapabilityDependencies,
  getCapabilityRemovalBlock,
  canRemoveCapability,
  toggleCapability,
  type CapabilityDependencyRule,
  type RemovalBlock,
  type FoundationId,
} from "./branching";

export { classifyIdeaKeywords } from "./classifier/keyword";

export { buildReviewSummary } from "./summary";
