export const ESTIMATE_PDF_DISCLAIMER =
  "This is not an official quotation. It is an indicative planning estimate generated by the Project Blueprint tool. A Good Code specialist must review scope before any formal quote.";

export const ESTIMATE_PDF_CONTACT =
  "Good Code · info@goodcode.com · +27 12 345 6789 · https://www.goodcode.co.za";
