/**
 * Production question catalogue for Project Blueprint.
 * Calm Good Code voice — practical, clear, no gimmicks.
 */

import type { ProjectBlueprintAnswers } from "../types";
import {
  hasIntegrations,
  needsAiFollowUps,
  needsCloudFollowUps,
  needsDeadlineConflictFollowUps,
  needsExistingProductFollowUps,
  needsKycFollowUps,
  needsLegacyFollowUps,
  needsMobileFollowUps,
  needsMultiTenantFollowUps,
  needsNativeMobileFollowUps,
  needsPaymentsFollowUps,
  needsRegulatedFollowUps,
} from "../branching/rules";
import {
  ADVICE_OPTIONS,
  DEFAULT_UNKNOWN_OPTIONS,
  UNSURE_ONLY,
  type FollowUpDefinition,
  type QuestionCatalogue,
  type QuestionDefinition,
  type ScreenDefinition,
} from "./schema";

const screens: ScreenDefinition[] = [
  {
    id: "route",
    title: "What are you planning to build?",
    summary: "Choose the closest starting shape so we can route you correctly.",
    helpText:
      "Website packages cover marketing and brochure sites. Everything else continues into Project Blueprint.",
    order: 0,
    questionIds: ["q.route.product_type"],
  },
  {
    id: "context",
    title: "Project context",
    summary: "Where you are starting from, and the outcome that matters most.",
    helpText: "This shapes discovery needs, reuse assumptions, and delivery risk.",
    order: 1,
    questionIds: ["q.context.starting_point", "q.context.primary_outcome"],
  },
  {
    id: "surfaces",
    title: "Product surfaces",
    summary: "Where people will interact with the product.",
    helpText: "Select every channel that must ship in the first meaningful release.",
    order: 2,
    questionIds: ["q.surfaces.channels"],
  },
  {
    id: "users",
    title: "Users, roles, and scale",
    summary: "Who uses the product, how many, and how access is organised.",
    helpText: "Approximate bands are enough — exact counts can wait.",
    order: 3,
    questionIds: [
      "q.users.groups",
      "q.users.scale",
      "q.users.role_count",
      "q.users.permissions",
      "q.users.multi_tenant",
      "q.users.transaction_volume",
      "q.users.regions",
      "q.users.languages",
      "q.users.currencies",
    ],
  },
  {
    id: "capabilities",
    title: "Core capabilities",
    summary: "The features that define the product’s job.",
    helpText: "Choose what the first release must do. Optional ideas can wait.",
    order: 4,
    questionIds: [
      "q.cap.access",
      "q.cap.workflows",
      "q.cap.payments",
      "q.cap.data",
      "q.cap.comms",
      "q.cap.intelligence",
    ],
  },
  {
    id: "integrations",
    title: "Integrations and migration",
    summary: "External systems to connect, and any data that must move.",
    helpText: "Integrations and data quality often drive both cost and uncertainty.",
    order: 5,
    questionIds: ["q.integrations.systems", "q.integrations.migration"],
  },
  {
    id: "quality",
    title: "Quality, security, and delivery risk",
    summary: "Sensitivity, compliance, reliability, and assurance expectations.",
    helpText: "These requirements protect users and widen scope when they are material.",
    order: 6,
    questionIds: ["q.quality.requirements"],
  },
  {
    id: "delivery",
    title: "Delivery readiness",
    summary: "Assets you already have, target product level, and timing.",
    helpText: "Budget is optional and is stored only as commercial context — it never changes the calculation.",
    order: 7,
    questionIds: [
      "q.delivery.assets",
      "q.delivery.product_level",
      "q.delivery.timing",
      "q.delivery.budget",
    ],
  },
  {
    id: "review",
    title: "Review your blueprint",
    summary: "Confirm the plain-language summary before we build your planning estimate.",
    helpText: "You can edit any section. Unknowns are highlighted so the range stays honest.",
    order: 8,
    questionIds: [],
  },
];

const questions: QuestionDefinition[] = [
  {
    id: "q.route.product_type",
    screenId: "route",
    inputType: "single_select",
    prompt: "What are you planning to build?",
    helpText:
      "Pick the closest match. If you need a standard marketing website, we’ll send you to website packages instead of this estimator.",
    supportingText: "Custom products continue into Project Blueprint.",
    answerKey: "route",
    required: true,
    unknownOptions: [
      {
        id: "not_sure",
        label: "I am not sure yet",
        helpText: "We’ll start with a broad custom-product path and refine as you answer.",
      },
      ...ADVICE_OPTIONS.filter((o) => o.id === "need_advice"),
    ],
    validationMessage: "Choose the closest product type to continue.",
    options: [
      {
        id: "route.website",
        label: "A business or marketing website",
        description: "Marketing sites, brochure websites, landing pages, blogs, and standard enquiries.",
        helpText: "Best served by fixed website packages rather than a custom estimate.",
        whenToChoose: "You mainly need to present the business and collect enquiries.",
        routesAway: "website_packages",
        tags: ["website"],
      },
      {
        id: "route.custom_web_platform",
        label: "A custom web platform",
        description: "A product with its own workflows, accounts, or business logic.",
        helpText: "Use this when the site is the product, not a brochure.",
        tags: ["web", "platform"],
      },
      {
        id: "route.customer_portal",
        label: "A customer or client portal",
        description: "Signed-in experiences for customers, clients, or partners.",
        tags: ["portal"],
      },
      {
        id: "route.internal_system",
        label: "An internal business system",
        description: "Tools for staff, operations, approvals, or back-office work.",
        tags: ["internal"],
      },
      {
        id: "route.mobile_app",
        label: "A mobile application",
        description: "iOS and Android apps, with or without a companion web product.",
        tags: ["mobile"],
      },
      {
        id: "route.saas_multi_tenant",
        label: "A SaaS or multi-tenant product",
        description: "One product serving multiple organisations with separated data.",
        tags: ["saas", "multi-tenant"],
      },
      {
        id: "route.api_integration",
        label: "An API or integration",
        description: "Connecting systems, exposing APIs, or automating exchanges of data.",
        tags: ["api", "integration"],
      },
      {
        id: "route.cloud_modernisation",
        label: "A cloud or modernisation project",
        description: "Infrastructure, hosting, migration, or platform modernisation.",
        tags: ["cloud"],
      },
      {
        id: "route.audit_roadmap",
        label: "A technical audit or product roadmap",
        description: "Assessment, architecture advice, and a clearer delivery plan.",
        tags: ["discovery", "audit"],
      },
      {
        id: "route.unsure",
        label: "I am not sure yet",
        description: "We’ll start broad and refine the product shape as you answer.",
        whenToChoose: "Use this when several options feel plausible.",
        tags: ["discovery"],
      },
    ],
  },
  {
    id: "q.context.starting_point",
    screenId: "context",
    inputType: "single_select",
    prompt: "Where are you starting from?",
    helpText:
      "Starting point affects discovery, reuse of existing work, and how much technical uncertainty we should expect.",
    answerKey: "startingPoint",
    required: true,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      {
        id: "start.new_idea",
        label: "New idea",
        description: "Early thinking; requirements are still forming.",
        whenToChoose: "You know the problem, but the product shape is still open.",
      },
      {
        id: "start.validated_concept",
        label: "Validated concept",
        description: "You have evidence the problem is worth solving.",
        whenToChoose: "Stakeholders agree on the need and a rough solution direction.",
      },
      {
        id: "start.existing_prototype",
        label: "Existing prototype",
        description: "Clickable or technical prototype exists and should inform the build.",
      },
      {
        id: "start.existing_product",
        label: "Existing product that needs new features",
        description: "A live product needs extension, not a greenfield rebuild.",
        tags: ["existing"],
      },
      {
        id: "start.legacy_replacement",
        label: "Legacy system that needs replacement",
        description: "An older system must be replaced or substantially modernised.",
        tags: ["legacy"],
      },
      {
        id: "start.connect_systems",
        label: "Existing systems that need to be connected",
        description: "The main job is integration rather than a brand-new product UI.",
        tags: ["integration"],
      },
      {
        id: "start.stabilisation_scaling",
        label: "Product that needs stabilisation or scaling",
        description: "Reliability, performance, or maintainability is the priority.",
        tags: ["existing", "scale"],
      },
      {
        id: "start.needs_discovery",
        label: "We need discovery before we know",
        description: "Scope is too uncertain for a confident build plan yet.",
        whenToChoose: "Choose this if workshops, audit, or roadmap work should come first.",
        tags: ["discovery"],
      },
    ],
  },
  {
    id: "q.context.primary_outcome",
    screenId: "context",
    inputType: "single_select",
    prompt: "What outcome matters most?",
    helpText: "We’ll use this to prioritise the recommended first release and explain trade-offs.",
    answerKey: "primaryOutcome",
    required: true,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      {
        id: "outcome.revenue_product",
        label: "Launch a new revenue-generating product",
        description: "Get a sellable or billable product into market.",
      },
      {
        id: "outcome.reduce_manual_work",
        label: "Reduce manual work",
        description: "Replace repetitive operational effort with reliable workflows.",
      },
      {
        id: "outcome.improve_customer_service",
        label: "Improve customer service",
        description: "Make it easier for customers to self-serve or get support.",
      },
      {
        id: "outcome.replace_spreadsheets",
        label: "Replace spreadsheets or disconnected tools",
        description: "Bring scattered processes into one dependable system.",
      },
      {
        id: "outcome.support_scale",
        label: "Support more users or transactions",
        description: "Grow capacity without the current process breaking down.",
      },
      {
        id: "outcome.improve_security",
        label: "Improve security or reliability",
        description: "Reduce operational risk, downtime, or security exposure.",
      },
      {
        id: "outcome.regulatory",
        label: "Meet regulatory or operational requirements",
        description: "Satisfy compliance, audit, or mandated process controls.",
      },
      {
        id: "outcome.modernise",
        label: "Modernise an existing platform",
        description: "Move off fragile technology or outdated architecture.",
      },
    ],
  },
  {
    id: "q.surfaces.channels",
    screenId: "surfaces",
    inputType: "multi_select",
    prompt: "Which product surfaces are required?",
    helpText:
      "Select every surface needed for the first release. You can keep later channels for a later phase.",
    answerKey: "surfaces",
    required: true,
    allowMultiple: true,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    validationMessage: "Select at least one surface, or choose an unknown option.",
    options: [
      {
        id: "surface.public_web",
        label: "Public web application",
        description: "Open or lightly gated web experience.",
        helpText: "Marketing-adjacent product UI, catalogues, or public tools.",
      },
      {
        id: "surface.customer_portal",
        label: "Authenticated customer portal",
        description: "Signed-in customer or client workspace.",
      },
      {
        id: "surface.admin_workspace",
        label: "Internal administration workspace",
        description: "Staff tools for configuration, support, or operations.",
      },
      {
        id: "surface.mobile_web",
        label: "Responsive mobile web experience",
        description: "Mobile-friendly browser experience without app stores.",
      },
      {
        id: "surface.native_mobile",
        label: "iOS and Android mobile application",
        description: "Installed mobile apps distributed through app stores.",
        tags: ["mobile"],
      },
      {
        id: "surface.public_api",
        label: "Public or partner API",
        description: "Programmatic access for partners or external systems.",
      },
      {
        id: "surface.background_jobs",
        label: "Background jobs or workflow automation",
        description: "Scheduled processing, queues, or unattended workflows.",
      },
      {
        id: "surface.reporting",
        label: "Reporting and analytics environment",
        description: "Dashboards, operational reports, or analytical views.",
      },
      {
        id: "surface.cloud_platform",
        label: "Cloud infrastructure or deployment platform",
        description: "Environments, deployment, hosting, and platform operations.",
        tags: ["cloud"],
      },
    ],
  },
  {
    id: "q.users.groups",
    screenId: "users",
    inputType: "multi_select",
    prompt: "Who will use the product?",
    helpText: "Select all groups that need a distinct experience or permission set.",
    answerKey: "userGroups",
    required: true,
    allowMultiple: true,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "users.customers", label: "Customers", description: "People buying or receiving your service." },
      { id: "users.employees", label: "Internal employees", description: "Day-to-day staff users." },
      { id: "users.administrators", label: "Administrators", description: "People who configure and govern the system." },
      { id: "users.managers", label: "Managers and approvers", description: "People who review, approve, or oversee work." },
      { id: "users.partners", label: "Partners or suppliers", description: "External organisations collaborating in the workflow." },
      { id: "users.merchants", label: "Merchants", description: "Sellers or service providers operating on the platform." },
      { id: "users.investors", label: "Investors", description: "Read-focused stakeholders with limited operational access." },
      { id: "users.field_teams", label: "Field teams", description: "People working on-site, often on mobile." },
      {
        id: "users.tenants",
        label: "Multiple client organisations or tenants",
        description: "Separate organisations sharing one product with isolated data.",
        tags: ["multi-tenant"],
      },
      { id: "users.public", label: "Public users", description: "Anonymous or lightly identified visitors." },
    ],
  },
  {
    id: "q.users.scale",
    screenId: "users",
    inputType: "single_select",
    prompt: "Approximately how many users?",
    helpText: "Use a planning band. Exact licence counts are not required here.",
    answerKey: "userScale",
    required: true,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "scale.under_100", label: "Fewer than 100 users" },
      { id: "scale.100_1000", label: "100–1,000" },
      { id: "scale.1000_10000", label: "1,000–10,000" },
      { id: "scale.10000_100000", label: "10,000–100,000" },
      { id: "scale.over_100000", label: "More than 100,000" },
      { id: "scale.unknown", label: "Unknown", helpText: "We’ll keep capacity assumptions conservative." },
    ],
  },
  {
    id: "q.users.role_count",
    screenId: "users",
    inputType: "single_select",
    prompt: "How many distinct user roles do you expect?",
    helpText: "Roles drive permissions design, testing, and administration screens.",
    answerKey: "roleCountBand",
    required: true,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "roles.1_2", label: "1–2 roles", description: "Simple access model." },
      { id: "roles.3_5", label: "3–5 roles", description: "Typical product with staff and customer separation." },
      { id: "roles.6_plus", label: "6 or more roles", description: "Richer permission and workflow design." },
    ],
  },
  {
    id: "q.users.permissions",
    screenId: "users",
    inputType: "boolean",
    prompt: "Do you need role-based permissions?",
    helpText: "Different roles see different screens or can perform different actions.",
    answerKey: "roleBasedPermissions",
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes", description: "Access differs by role." },
      { id: "no", label: "No", description: "All signed-in users share the same access." },
    ],
  },
  {
    id: "q.users.multi_tenant",
    screenId: "users",
    inputType: "boolean",
    prompt: "Does the product serve multiple organisations as separate tenants?",
    helpText: "Multi-tenant products need stronger data separation and tenant administration.",
    answerKey: "multiTenant",
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes", description: "Each organisation’s data and settings stay separate." },
      { id: "no", label: "No", description: "One organisation owns the product and its data." },
    ],
  },
  {
    id: "q.users.transaction_volume",
    screenId: "users",
    inputType: "single_select",
    prompt: "Expected transaction or workflow volume?",
    helpText: "Rough throughput helps us judge performance, queuing, and operational tooling.",
    answerKey: "transactionVolume",
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "volume.low", label: "Low", description: "Dozens to a few hundred meaningful events per day." },
      { id: "volume.moderate", label: "Moderate", description: "Steady daily operational load." },
      { id: "volume.high", label: "High", description: "Busy production traffic or peak bursts." },
      { id: "volume.unknown", label: "Unknown" },
    ],
  },
  {
    id: "q.users.regions",
    screenId: "users",
    inputType: "single_select",
    prompt: "How many countries or regions matter for the first release?",
    helpText: "Regions can affect compliance, data residency, payments, and localisation.",
    answerKey: "countriesOrRegions",
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "regions.one", label: "One country or region" },
      { id: "regions.few", label: "A few countries or regions" },
      { id: "regions.many", label: "Many countries or regions" },
    ],
  },
  {
    id: "q.users.languages",
    screenId: "users",
    inputType: "boolean",
    prompt: "Do you need multiple languages in the first release?",
    helpText: "Extra languages add content, UI, and testing effort.",
    answerKey: "multipleLanguages",
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No — one language is enough for now" },
    ],
  },
  {
    id: "q.users.currencies",
    screenId: "users",
    inputType: "boolean",
    prompt: "Do you need multiple currencies?",
    helpText: "Relevant for payments, invoicing, reporting, and pricing displays.",
    answerKey: "multipleCurrencies",
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No — a single currency is enough" },
    ],
  },
  {
    id: "q.cap.access",
    screenId: "capabilities",
    inputType: "multi_select",
    prompt: "Access and onboarding",
    helpText: "How people register, sign in, and receive the right level of access.",
    answerKey: "capabilities",
    allowMultiple: true,
    groupId: "cap.group.access",
    groupLabel: "Access and onboarding",
    unknownOptions: [
      {
        id: "help_me_choose",
        label: "Help me choose",
        helpText: "Most authenticated products need registration, login, and role management as a baseline.",
      },
      {
        id: "not_sure",
        label: "I’m not sure",
        helpText: "We’ll assume standard authentication if the product is signed-in, and confirm on review.",
      },
    ],
    options: [
      { id: "cap.access.registration_login", label: "Account registration and login" },
      { id: "cap.access.social_login", label: "Social login" },
      { id: "cap.access.mfa", label: "Multi-factor authentication" },
      { id: "cap.access.sso", label: "Single sign-on" },
      { id: "cap.access.invitations", label: "User invitations" },
      {
        id: "cap.access.kyc",
        label: "Identity verification or KYC",
        helpText: "Document checks, provider verification, or manual identity review.",
        tags: ["kyc", "regulated"],
      },
      { id: "cap.access.org_onboarding", label: "Organisation onboarding" },
      { id: "cap.access.role_permissions", label: "Role and permission management" },
    ],
  },
  {
    id: "q.cap.workflows",
    screenId: "capabilities",
    inputType: "multi_select",
    prompt: "Business workflows",
    helpText: "The operational paths people follow inside the product.",
    answerKey: "capabilities",
    allowMultiple: true,
    groupId: "cap.group.workflows",
    groupLabel: "Business workflows",
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "cap.workflow.forms", label: "Forms and data capture" },
      { id: "cap.workflow.multi_step", label: "Multi-step applications" },
      { id: "cap.workflow.approvals", label: "Reviews and approvals" },
      { id: "cap.workflow.task_assignment", label: "Task assignment" },
      { id: "cap.workflow.status_tracking", label: "Status tracking" },
      { id: "cap.workflow.rules_calculations", label: "Rules and calculations" },
      { id: "cap.workflow.scheduling", label: "Scheduling" },
      { id: "cap.workflow.case_management", label: "Case management" },
      { id: "cap.workflow.configurable", label: "Configurable workflows" },
    ],
  },
  {
    id: "q.cap.payments",
    screenId: "capabilities",
    inputType: "multi_select",
    prompt: "Payments and commercial features",
    helpText: "Money movement, billing, and commercial settlement inside the product.",
    answerKey: "capabilities",
    allowMultiple: true,
    groupId: "cap.group.payments",
    groupLabel: "Payments and commercial features",
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "cap.payments.one_time", label: "One-time payments", tags: ["payments"] },
      { id: "cap.payments.recurring", label: "Recurring billing", tags: ["payments"] },
      { id: "cap.payments.subscriptions", label: "Subscriptions", tags: ["payments"] },
      { id: "cap.payments.invoices", label: "Invoices", tags: ["payments"] },
      { id: "cap.payments.refunds", label: "Refunds", tags: ["payments"] },
      { id: "cap.payments.payouts", label: "Payouts to third parties", tags: ["payments"] },
      { id: "cap.payments.marketplace", label: "Marketplace transactions", tags: ["payments"] },
      { id: "cap.payments.multi_currency", label: "Multiple currencies", tags: ["payments"] },
      { id: "cap.payments.reconciliation", label: "Payment reconciliation", tags: ["payments"] },
      {
        id: "cap.payments.financial_schedules",
        label: "Financial schedules or loan-related calculations",
        tags: ["payments"],
      },
    ],
  },
  {
    id: "q.cap.data",
    screenId: "capabilities",
    inputType: "multi_select",
    prompt: "Data and content",
    helpText: "How information is stored, found, reported, and retained.",
    answerKey: "capabilities",
    allowMultiple: true,
    groupId: "cap.group.data",
    groupLabel: "Data and content",
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "cap.data.dashboards", label: "Dashboards" },
      { id: "cap.data.reports", label: "Reports" },
      { id: "cap.data.exports", label: "Exports" },
      { id: "cap.data.search", label: "Search and filtering" },
      { id: "cap.data.files", label: "File and document management" },
      { id: "cap.data.signatures", label: "Digital signatures" },
      { id: "cap.data.cms", label: "Content management" },
      { id: "cap.data.audit_history", label: "Audit history" },
      { id: "cap.data.visualisation", label: "Data visualisation" },
      { id: "cap.data.geospatial", label: "Geospatial or map features" },
    ],
  },
  {
    id: "q.cap.comms",
    screenId: "capabilities",
    inputType: "multi_select",
    prompt: "Communication",
    helpText: "How the product notifies people and keeps conversations in context.",
    answerKey: "capabilities",
    allowMultiple: true,
    groupId: "cap.group.comms",
    groupLabel: "Communication",
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "cap.comms.email", label: "Email notifications" },
      { id: "cap.comms.sms_whatsapp", label: "SMS or WhatsApp notifications" },
      { id: "cap.comms.push", label: "Push notifications" },
      { id: "cap.comms.in_product", label: "In-product notifications" },
      { id: "cap.comms.realtime", label: "Real-time updates" },
      { id: "cap.comms.chat", label: "Chat or messaging" },
    ],
  },
  {
    id: "q.cap.intelligence",
    screenId: "capabilities",
    inputType: "multi_select",
    prompt: "Intelligence and automation",
    helpText: "Rules, automation, and AI-assisted work that changes delivery risk and evaluation needs.",
    answerKey: "capabilities",
    allowMultiple: true,
    groupId: "cap.group.intelligence",
    groupLabel: "Intelligence and automation",
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "cap.ai.automated_rules", label: "Automated rules", tags: ["ai"] },
      { id: "cap.ai.document_extraction", label: "Document extraction", tags: ["ai"] },
      { id: "cap.ai.search", label: "AI-assisted search", tags: ["ai"] },
      { id: "cap.ai.summaries", label: "AI-generated summaries", tags: ["ai"] },
      { id: "cap.ai.recommendations", label: "Recommendations", tags: ["ai"] },
      { id: "cap.ai.forecasting", label: "Forecasting", tags: ["ai"] },
      { id: "cap.ai.human_reviewed", label: "Human-reviewed AI workflows", tags: ["ai"] },
      { id: "cap.ai.process_automation", label: "Process automation", tags: ["ai"] },
    ],
  },
  {
    id: "q.integrations.systems",
    screenId: "integrations",
    inputType: "multi_select",
    prompt: "Which systems must this product connect to?",
    helpText:
      "Select known systems now. Unknown integrations can be marked and refined during review or discovery.",
    answerKey: "integrations",
    allowMultiple: true,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "integration.payment_gateway", label: "Payment gateway" },
      { id: "integration.accounting_erp", label: "Accounting or ERP" },
      { id: "integration.crm", label: "CRM" },
      { id: "integration.banking", label: "Banking system" },
      { id: "integration.identity_credit", label: "Identity or credit provider" },
      { id: "integration.mapping", label: "Mapping or location platform" },
      { id: "integration.messaging", label: "Email, SMS, or WhatsApp service" },
      { id: "integration.esignature", label: "Document-signing provider" },
      { id: "integration.cloud_storage", label: "Cloud storage" },
      { id: "integration.internal_system", label: "Existing internal system" },
      { id: "integration.government", label: "Government or regulatory service" },
      { id: "integration.analytics", label: "Analytics platform" },
      { id: "integration.other_api", label: "Other external API" },
      {
        id: "integration.none",
        label: "No integrations",
        description: "The first release can stand alone.",
      },
      {
        id: "integration.unknown",
        label: "Unknown",
        description: "Connections exist or may exist, but details are unclear.",
      },
    ],
  },
  {
    id: "q.integrations.migration",
    screenId: "integrations",
    inputType: "single_select",
    prompt: "What does data migration look like?",
    helpText: "Migration quality and volume often affect timeline more than people expect.",
    answerKey: "migrationProfile",
    required: true,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "migration.none", label: "No existing data" },
      { id: "migration.spreadsheet", label: "Spreadsheet or CSV import" },
      { id: "migration.standard_db", label: "Standard database migration" },
      { id: "migration.multiple_sources", label: "Multiple data sources" },
      { id: "migration.poor_structure", label: "Poorly structured or incomplete data" },
      { id: "migration.large_history", label: "Large historical data volume" },
      { id: "migration.unknown", label: "Migration complexity unknown" },
    ],
  },
  {
    id: "q.quality.requirements",
    screenId: "quality",
    inputType: "multi_select",
    prompt: "Which quality, security, and delivery expectations apply?",
    helpText: "Select requirements that are genuinely needed. Overstating them widens cost without improving fit.",
    answerKey: "qualityRequirements",
    allowMultiple: true,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "quality.personal_sensitive", label: "Personal or sensitive information" },
      { id: "quality.financial_info", label: "Financial information", tags: ["regulated"] },
      { id: "quality.identity_documents", label: "Identity documents", tags: ["regulated"] },
      { id: "quality.payment_card_info", label: "Payment-card information", tags: ["regulated", "payments"] },
      { id: "quality.audit_traceability", label: "Audit and traceability requirements", tags: ["regulated"] },
      { id: "quality.popia_privacy", label: "POPIA or other privacy obligations", tags: ["regulated"] },
      { id: "quality.industry_compliance", label: "Industry-specific compliance", tags: ["regulated"] },
      { id: "quality.data_residency", label: "Data residency" },
      { id: "quality.high_availability", label: "High availability" },
      { id: "quality.disaster_recovery", label: "Disaster recovery" },
      { id: "quality.performance_critical", label: "Performance-critical workflows" },
      { id: "quality.high_transaction_volumes", label: "High transaction volumes" },
      { id: "quality.pen_test", label: "Penetration testing" },
      { id: "quality.security_review", label: "Independent security review" },
      { id: "quality.accessibility", label: "Accessibility requirements" },
      { id: "quality.uat", label: "Formal user-acceptance testing" },
      { id: "quality.regression", label: "Automated regression testing" },
      { id: "quality.monitoring", label: "Monitoring and observability" },
      { id: "quality.sla", label: "Service-level commitments" },
    ],
  },
  {
    id: "q.delivery.assets",
    screenId: "delivery",
    inputType: "multi_select",
    prompt: "What do you already have?",
    helpText: "Existing assets can reduce design and discovery effort when they are usable.",
    answerKey: "existingAssets",
    allowMultiple: true,
    unknownOptions: [
      {
        id: "not_sure",
        label: "I’m not sure what counts",
        helpText: "If in doubt, select only artefacts you can share soon.",
      },
      {
        id: "need_advice",
        label: "We need advice",
        helpText: "We can help judge what is reusable during discovery.",
      },
    ],
    options: [
      { id: "asset.brief", label: "Product brief" },
      { id: "asset.user_research", label: "User research" },
      { id: "asset.wireframes", label: "Wireframes" },
      { id: "asset.final_designs", label: "Final designs" },
      { id: "asset.brand_system", label: "Brand system" },
      { id: "asset.architecture", label: "Technical architecture" },
      { id: "asset.source_code", label: "Existing source code" },
      { id: "asset.api_docs", label: "API documentation" },
      { id: "asset.test_environment", label: "Test environment" },
      { id: "asset.product_owner", label: "Internal product owner" },
      { id: "asset.nothing", label: "Nothing formal yet" },
    ],
  },
  {
    id: "q.delivery.product_level",
    screenId: "delivery",
    inputType: "single_select",
    prompt: "What level of product are you aiming for?",
    helpText: "This sets the finish line for the first release we estimate.",
    answerKey: "productLevel",
    required: true,
    unknownOptions: [
      {
        id: "not_sure",
        label: "Not sure",
        helpText: "We’ll default toward a production-ready MVP and confirm on review.",
      },
      {
        id: "help_me_choose",
        label: "Help me choose",
        helpText: "Most teams start with a lean validation release or production-ready MVP.",
      },
    ],
    options: [
      { id: "level.prototype", label: "Clickable prototype", description: "Explore experience and direction without full build-out." },
      { id: "level.poc", label: "Technical proof of concept", description: "Prove a technical approach under realistic constraints." },
      { id: "level.lean_validation", label: "Lean validation release", description: "Smallest useful release to learn from real users." },
      { id: "level.production_mvp", label: "Production-ready MVP", description: "Reliable first product that can operate in production." },
      { id: "level.scale_ready", label: "Scale-ready product", description: "Built for growth, operational maturity, and harder non-functionals." },
      {
        id: "level.enterprise_regulated",
        label: "Enterprise or regulated platform",
        description: "Higher assurance, governance, and compliance expectations.",
      },
      { id: "level.not_sure", label: "Not sure" },
    ],
  },
  {
    id: "q.delivery.timing",
    screenId: "delivery",
    inputType: "single_select",
    prompt: "What timing are you aiming for?",
    helpText:
      "Desired dates guide planning. We will not promise an unrealistic deadline against the selected scope.",
    answerKey: "timing",
    required: true,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "timing.no_deadline", label: "No fixed deadline" },
      { id: "timing.within_3_months", label: "Within three months" },
      { id: "timing.3_to_6_months", label: "Three to six months" },
      { id: "timing.6_to_12_months", label: "Six to twelve months" },
      { id: "timing.over_12_months", label: "More than twelve months" },
      {
        id: "timing.date_required",
        label: "Date required for a commercial or regulatory reason",
        helpText: "Tell us on review; we will check whether scope and date can coexist.",
      },
      { id: "timing.not_sure", label: "I’m not sure" },
    ],
  },
  {
    id: "q.delivery.budget",
    screenId: "delivery",
    inputType: "budget_band",
    prompt: "Optional: what budget band are you working with?",
    helpText:
      "Budget is optional commercial context only. It never reduces or inflates the technical calculation.",
    supportingText: "Skip this if you prefer not to share a number yet.",
    answerKey: "budgetBand",
    required: false,
    unknownOptions: [
      {
        id: "not_sure",
        label: "Prefer not to say",
        helpText: "Completely fine — the estimate will still calculate from scope.",
      },
      {
        id: "need_advice",
        label: "We need advice on budget",
        helpText: "We can discuss commercial fit after the planning range is clear.",
      },
    ],
    options: [
      { id: "budget.under_250k", label: "Under R250k" },
      { id: "budget.250k_500k", label: "R250k–R500k" },
      { id: "budget.500k_1m", label: "R500k–R1m" },
      { id: "budget.1m_2m", label: "R1m–R2m" },
      { id: "budget.2m_plus", label: "R2m+" },
      { id: "budget.flexible", label: "Flexible / still forming" },
    ],
  },
];

const followUps: FollowUpDefinition[] = [
  {
    id: "q.followup.mobile.push",
    parentQuestionId: "q.surfaces.channels",
    screenId: "surfaces",
    inputType: "boolean",
    prompt: "Do you need push notifications?",
    helpText: "Push adds provider setup, permission flows, and notification content work.",
    answerKey: "mobileFollowUps.pushNotifications",
    when: needsMobileFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
    ],
  },
  {
    id: "q.followup.mobile.offline",
    parentQuestionId: "q.surfaces.channels",
    screenId: "surfaces",
    inputType: "boolean",
    prompt: "Is offline capability required?",
    helpText: "Offline use affects data sync, conflict handling, and testing effort.",
    answerKey: "mobileFollowUps.offlineCapability",
    when: needsNativeMobileFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No — online use is enough" },
    ],
  },
  {
    id: "q.followup.mobile.device",
    parentQuestionId: "q.surfaces.channels",
    screenId: "surfaces",
    inputType: "multi_select",
    prompt: "Which device capabilities matter?",
    helpText: "Camera, location, biometrics, and similar features change mobile delivery effort.",
    answerKey: "mobileFollowUps.deviceFeatures",
    when: needsNativeMobileFollowUps,
    allowMultiple: true,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "device.camera", label: "Camera" },
      { id: "device.location", label: "Location" },
      { id: "device.biometrics", label: "Biometrics" },
      { id: "device.other", label: "Other device functions" },
      { id: "device.none", label: "None of these" },
    ],
  },
  {
    id: "q.followup.mobile.stores",
    parentQuestionId: "q.surfaces.channels",
    screenId: "surfaces",
    inputType: "boolean",
    prompt: "Do you need App Store and Play Store deployment?",
    helpText: "Store release includes listing assets, review cycles, and release process.",
    answerKey: "mobileFollowUps.storeDeployment",
    when: needsNativeMobileFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No — internal or web distribution only" },
    ],
  },
  {
    id: "q.followup.mobile.platform",
    parentQuestionId: "q.surfaces.channels",
    screenId: "surfaces",
    inputType: "single_select",
    prompt: "Preferred mobile platform strategy?",
    helpText: "Cross-platform and native approaches have different cost and constraint profiles.",
    answerKey: "mobileFollowUps.platformStrategy",
    when: needsNativeMobileFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      {
        id: "cross_platform",
        label: "Shared cross-platform build",
        description: "One codebase targeting iOS and Android where practical.",
      },
      {
        id: "native",
        label: "Native applications",
        description: "Separate native builds where platform-specific behaviour matters.",
      },
    ],
  },
  {
    id: "q.followup.mobile.tablet",
    parentQuestionId: "q.surfaces.channels",
    screenId: "surfaces",
    inputType: "boolean",
    prompt: "Are tablet-specific workflows required?",
    helpText: "Tablet layouts and interactions are additional product surfaces to design and test.",
    answerKey: "mobileFollowUps.tabletWorkflows",
    when: needsMobileFollowUps,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
    ],
  },
  {
    id: "q.followup.payments.modes",
    parentQuestionId: "q.cap.payments",
    screenId: "capabilities",
    inputType: "multi_select",
    prompt: "Which payment behaviours are in scope?",
    helpText: "Payment shape drives provider setup, edge cases, and reconciliation design.",
    answerKey: "paymentsFollowUps.paymentModes",
    when: needsPaymentsFollowUps,
    allowMultiple: true,
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "pay.mode.one_time", label: "One-time payments" },
      { id: "pay.mode.recurring", label: "Recurring or subscription billing" },
      { id: "pay.mode.refunds", label: "Refunds" },
      { id: "pay.mode.payouts", label: "Payouts" },
      { id: "pay.mode.marketplace", label: "Marketplace split payments" },
    ],
  },
  {
    id: "q.followup.payments.tokenisation",
    parentQuestionId: "q.cap.payments",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Do you need card tokenisation or saved payment methods?",
    helpText: "Saved methods require careful provider and security handling.",
    answerKey: "paymentsFollowUps.tokenisation",
    when: needsPaymentsFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
    ],
  },
  {
    id: "q.followup.payments.reconciliation",
    parentQuestionId: "q.cap.payments",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Is payment reconciliation required?",
    helpText: "Matching provider settlements to internal records adds operational design.",
    answerKey: "paymentsFollowUps.reconciliation",
    when: needsPaymentsFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Not for the first release" },
    ],
  },
  {
    id: "q.followup.payments.certification",
    parentQuestionId: "q.cap.payments",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Is provider certification or approval required?",
    helpText: "Certification cycles can extend timeline independently of engineering effort.",
    answerKey: "paymentsFollowUps.providerCertification",
    when: needsPaymentsFollowUps,
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No / not expected" },
    ],
  },
  {
    id: "q.followup.tenant.isolation",
    parentQuestionId: "q.users.multi_tenant",
    screenId: "users",
    inputType: "boolean",
    prompt: "Do tenants need strong data isolation?",
    helpText: "Isolation requirements influence architecture, testing, and operations.",
    answerKey: "multiTenantFollowUps.tenantIsolation",
    when: needsMultiTenantFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Basic separation is enough" },
    ],
  },
  {
    id: "q.followup.tenant.admin",
    parentQuestionId: "q.users.multi_tenant",
    screenId: "users",
    inputType: "boolean",
    prompt: "Do you need tenant administration tools?",
    helpText: "Tenant admins managing users, branding, or settings inside their organisation.",
    answerKey: "multiTenantFollowUps.tenantAdministration",
    when: needsMultiTenantFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Central admin only" },
    ],
  },
  {
    id: "q.followup.tenant.branding",
    parentQuestionId: "q.users.multi_tenant",
    screenId: "users",
    inputType: "boolean",
    prompt: "Do tenants need their own branding or configuration?",
    helpText: "Custom domains, themes, and per-tenant settings add product surface area.",
    answerKey: "multiTenantFollowUps.tenantBranding",
    when: needsMultiTenantFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Shared branding is fine" },
    ],
  },
  {
    id: "q.followup.tenant.domains",
    parentQuestionId: "q.users.multi_tenant",
    screenId: "users",
    inputType: "boolean",
    prompt: "Are custom domains required per tenant?",
    helpText: "Custom domains add DNS, certificates, and onboarding complexity.",
    answerKey: "multiTenantFollowUps.customDomains",
    when: needsMultiTenantFollowUps,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
    ],
  },
  {
    id: "q.followup.kyc.provider",
    parentQuestionId: "q.cap.access",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Will identity verification use an external provider?",
    helpText: "Provider integration, webhooks, and failure handling are usually required.",
    answerKey: "kycFollowUps.providerIntegration",
    when: needsKycFollowUps,
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Manual process only" },
    ],
  },
  {
    id: "q.followup.kyc.documents",
    parentQuestionId: "q.cap.access",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Is document capture part of onboarding?",
    helpText: "Uploads, image quality checks, and secure storage become part of scope.",
    answerKey: "kycFollowUps.documentCapture",
    when: needsKycFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
    ],
  },
  {
    id: "q.followup.kyc.liveness",
    parentQuestionId: "q.cap.access",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Are liveness checks required?",
    helpText: "Liveness adds provider cost, UX friction, and failure-path design.",
    answerKey: "kycFollowUps.livenessChecks",
    when: needsKycFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
    ],
  },
  {
    id: "q.followup.kyc.manual_review",
    parentQuestionId: "q.cap.access",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Do humans need to review borderline identity cases?",
    helpText: "Manual review queues, permissions, and audit trails usually follow.",
    answerKey: "kycFollowUps.manualReview",
    when: needsKycFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Automated decisioning only" },
    ],
  },
  {
    id: "q.followup.existing.ownership",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "single_select",
    prompt: "Who owns the existing code?",
    helpText: "Ownership affects access, handover, and how quickly we can assess the codebase.",
    answerKey: "existingProductFollowUps.codeOwnership",
    when: needsExistingProductFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "client", label: "Your organisation" },
      { id: "vendor", label: "A previous vendor" },
      { id: "shared", label: "Shared / unclear" },
    ],
  },
  {
    id: "q.followup.existing.docs",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "single_select",
    prompt: "How complete is the current documentation?",
    helpText: "Thin documentation increases discovery and onboarding effort.",
    answerKey: "existingProductFollowUps.documentationQuality",
    when: needsExistingProductFollowUps,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "good", label: "Good" },
      { id: "partial", label: "Partial" },
      { id: "poor", label: "Poor or missing" },
    ],
  },
  {
    id: "q.followup.existing.tests",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "single_select",
    prompt: "What test coverage exists today?",
    helpText: "Low coverage raises regression risk when extending an existing product.",
    answerKey: "existingProductFollowUps.testCoverage",
    when: needsExistingProductFollowUps,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "good", label: "Good automated coverage" },
      { id: "partial", label: "Partial coverage" },
      { id: "none", label: "Little or none" },
    ],
  },
  {
    id: "q.followup.existing.debt",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "single_select",
    prompt: "How significant is technical debt?",
    helpText: "Honest debt assessment protects the estimate from false confidence.",
    answerKey: "existingProductFollowUps.technicalDebt",
    when: needsExistingProductFollowUps,
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "low", label: "Low" },
      { id: "moderate", label: "Moderate" },
      { id: "high", label: "High" },
    ],
  },
  {
    id: "q.followup.existing.audit",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "boolean",
    prompt: "Should we include a technical audit before major delivery?",
    helpText: "Often the safest first step when extending or stabilising an existing product.",
    answerKey: "existingProductFollowUps.auditRequired",
    when: needsExistingProductFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Not necessary" },
    ],
  },
  {
    id: "q.followup.legacy.volume",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "single_select",
    prompt: "How large is the legacy migration?",
    helpText: "Volume and data quality drive cutover planning.",
    answerKey: "legacyFollowUps.migrationVolume",
    when: needsLegacyFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "small", label: "Small" },
      { id: "medium", label: "Medium" },
      { id: "large", label: "Large" },
    ],
  },
  {
    id: "q.followup.legacy.parallel",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "boolean",
    prompt: "Must old and new systems run in parallel for a period?",
    helpText: "Parallel operation adds integration, reconciliation, and operational overhead.",
    answerKey: "legacyFollowUps.parallelOperation",
    when: needsLegacyFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No — a cleaner cutover is acceptable" },
    ],
  },
  {
    id: "q.followup.legacy.cutover",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "single_select",
    prompt: "Preferred cutover approach?",
    helpText: "Phased cutovers reduce risk but extend dual-running effort.",
    answerKey: "legacyFollowUps.cutoverApproach",
    when: needsLegacyFollowUps,
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "big_bang", label: "Single cutover" },
      { id: "phased", label: "Phased cutover" },
    ],
  },
  {
    id: "q.followup.legacy.data_quality",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "single_select",
    prompt: "How would you describe legacy data quality?",
    helpText: "Poor data quality expands cleansing, mapping, and exception handling.",
    answerKey: "legacyFollowUps.dataQuality",
    when: needsLegacyFollowUps,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "good", label: "Good" },
      { id: "mixed", label: "Mixed" },
      { id: "poor", label: "Poor" },
    ],
  },
  {
    id: "q.followup.legacy.continuity",
    parentQuestionId: "q.context.starting_point",
    screenId: "context",
    inputType: "boolean",
    prompt: "Is uninterrupted business continuity required during replacement?",
    helpText: "Continuity constraints shape sequencing, fallbacks, and support planning.",
    answerKey: "legacyFollowUps.businessContinuity",
    when: needsLegacyFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "A planned outage window is acceptable" },
    ],
  },
  {
    id: "q.followup.ai.sensitivity",
    parentQuestionId: "q.cap.intelligence",
    screenId: "capabilities",
    inputType: "single_select",
    prompt: "How sensitive is the data used by AI or automation?",
    helpText: "Sensitivity affects provider choice, controls, and review requirements.",
    answerKey: "aiFollowUps.dataSensitivity",
    when: needsAiFollowUps,
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "low", label: "Low" },
      { id: "moderate", label: "Moderate" },
      { id: "high", label: "High" },
    ],
  },
  {
    id: "q.followup.ai.human_review",
    parentQuestionId: "q.cap.intelligence",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Should people review AI outputs before action is taken?",
    helpText: "Human review improves safety and adds workflow design.",
    answerKey: "aiFollowUps.humanReview",
    when: needsAiFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Automated action is acceptable" },
    ],
  },
  {
    id: "q.followup.ai.evaluation",
    parentQuestionId: "q.cap.intelligence",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Do you need formal evaluation of accuracy or usefulness?",
    helpText: "Evaluation protects against unverified AI behaviour entering production.",
    answerKey: "aiFollowUps.evaluationNeeded",
    when: needsAiFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Not for the first release" },
    ],
  },
  {
    id: "q.followup.ai.fallback",
    parentQuestionId: "q.cap.intelligence",
    screenId: "capabilities",
    inputType: "boolean",
    prompt: "Is a non-AI fallback path required when automation fails?",
    helpText: "Fallback paths keep operations moving when models or providers misbehave.",
    answerKey: "aiFollowUps.fallbackBehaviour",
    when: needsAiFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Not required yet" },
    ],
  },
  {
    id: "q.followup.cloud.environments",
    parentQuestionId: "q.surfaces.channels",
    screenId: "surfaces",
    inputType: "multi_select",
    prompt: "Which environments do you need?",
    helpText: "Environment count affects infrastructure, promotion flow, and operating cost.",
    answerKey: "cloudFollowUps.environments",
    when: needsCloudFollowUps,
    allowMultiple: true,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "env.dev", label: "Development" },
      { id: "env.staging", label: "Staging" },
      { id: "env.production", label: "Production" },
      { id: "env.dr", label: "Disaster recovery" },
    ],
  },
  {
    id: "q.followup.cloud.cicd",
    parentQuestionId: "q.route.product_type",
    screenId: "delivery",
    inputType: "boolean",
    prompt: "Do you need CI/CD as part of delivery?",
    helpText: "Automated build and deploy pipelines reduce release risk.",
    answerKey: "cloudFollowUps.cicd",
    when: needsCloudFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Manual releases are acceptable for now" },
    ],
  },
  {
    id: "q.followup.cloud.uptime",
    parentQuestionId: "q.route.product_type",
    screenId: "quality",
    inputType: "single_select",
    prompt: "Target uptime expectation?",
    helpText: "Higher uptime targets increase architecture and operational readiness work.",
    answerKey: "cloudFollowUps.uptimeTarget",
    when: needsCloudFollowUps,
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "standard", label: "Standard business hours reliability" },
      { id: "high", label: "High availability" },
      { id: "critical", label: "Business-critical availability" },
    ],
  },
  {
    id: "q.followup.cloud.monitoring",
    parentQuestionId: "q.route.product_type",
    screenId: "quality",
    inputType: "boolean",
    prompt: "Should monitoring and alerting be included from the start?",
    helpText: "Observability is usually essential for production systems.",
    answerKey: "cloudFollowUps.monitoring",
    when: needsCloudFollowUps,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Later" },
    ],
  },
  {
    id: "q.followup.integrations.docs",
    parentQuestionId: "q.integrations.systems",
    screenId: "integrations",
    inputType: "boolean",
    prompt: "Is integration documentation available for the systems involved?",
    helpText: "Missing documentation increases investigation and risk.",
    answerKey: "integrationDetails._shared.documentationAvailable",
    when: hasIntegrations,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "yes", label: "Yes, for the important systems" },
      { id: "no", label: "No / incomplete" },
    ],
  },
  {
    id: "q.followup.integrations.style",
    parentQuestionId: "q.integrations.systems",
    screenId: "integrations",
    inputType: "single_select",
    prompt: "What best describes the integration interfaces?",
    helpText: "Modern APIs are usually faster to integrate than legacy or undocumented systems.",
    answerKey: "integrationDetails._shared.apiStyle",
    when: hasIntegrations,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "modern_rest", label: "Modern REST API" },
      { id: "graphql", label: "GraphQL API" },
      { id: "legacy", label: "Legacy interface" },
      { id: "undocumented", label: "Undocumented or unclear" },
    ],
  },
  {
    id: "q.followup.integrations.sandbox",
    parentQuestionId: "q.integrations.systems",
    screenId: "integrations",
    inputType: "boolean",
    prompt: "Is a sandbox or test environment available?",
    helpText: "Without a sandbox, integration testing becomes slower and riskier.",
    answerKey: "integrationDetails._shared.sandboxAvailable",
    when: hasIntegrations,
    unknownOptions: UNSURE_ONLY,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "No" },
    ],
  },
  {
    id: "q.followup.integrations.sync",
    parentQuestionId: "q.integrations.systems",
    screenId: "integrations",
    inputType: "boolean",
    prompt: "Is two-way synchronisation required?",
    helpText: "Two-way sync adds conflict handling and operational monitoring.",
    answerKey: "integrationDetails._shared.twoWaySync",
    when: hasIntegrations,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "One-way is enough" },
    ],
  },
  {
    id: "q.followup.integrations.webhooks",
    parentQuestionId: "q.integrations.systems",
    screenId: "integrations",
    inputType: "boolean",
    prompt: "Are webhooks or real-time events required?",
    helpText: "Event-driven integrations need reliable delivery and failure handling.",
    answerKey: "integrationDetails._shared.webhooksRequired",
    when: hasIntegrations,
    unknownOptions: DEFAULT_UNKNOWN_OPTIONS,
    options: [
      { id: "yes", label: "Yes" },
      { id: "no", label: "Batch or on-demand is enough" },
    ],
  },
  {
    id: "q.followup.regulated.controls",
    parentQuestionId: "q.quality.requirements",
    screenId: "quality",
    inputType: "multi_select",
    prompt: "Which regulated-product controls apply?",
    helpText: "These controls often require explicit design, evidence, and operational process.",
    answerKey: "regulatedControls",
    when: needsRegulatedFollowUps,
    allowMultiple: true,
    unknownOptions: ADVICE_OPTIONS,
    options: [
      { id: "regulated.identity_verification", label: "Identity verification" },
      { id: "regulated.approval_audit_trails", label: "Approval or audit trails" },
      { id: "regulated.data_retention", label: "Data-retention requirements" },
      { id: "regulated.segregation_of_duties", label: "Segregation of duties" },
      { id: "regulated.fraud_controls", label: "Fraud controls" },
      { id: "regulated.transaction_reconciliation", label: "Transaction reconciliation" },
      { id: "regulated.external_reporting", label: "Reporting to external parties" },
      { id: "regulated.provider_certification", label: "Provider certification" },
      { id: "regulated.human_review", label: "Human review requirements" },
    ],
  },
  {
    id: "q.followup.deadline.resolution",
    parentQuestionId: "q.delivery.timing",
    screenId: "delivery",
    inputType: "single_select",
    prompt: "Your timing looks ambitious for the selected scope. How should we handle that?",
    helpText:
      "We will not invent an impossible date. Choose a planning approach so the estimate stays honest.",
    answerKey: "deadlineConflictResolution",
    when: needsDeadlineConflictFollowUps,
    unknownOptions: ADVICE_OPTIONS,
    options: [
      {
        id: "reduce_scope",
        label: "Reduce first-release scope",
        description: "Ship a thinner first version that can meet the date.",
      },
      {
        id: "increase_capacity",
        label: "Increase parallel delivery capacity",
        description: "Accept higher coordination cost to move faster.",
      },
      {
        id: "discovery_first",
        label: "Begin with a discovery phase",
        description: "Clarify scope and risks before committing to a fixed delivery window.",
      },
      {
        id: "phased_launch",
        label: "Use a phased launch",
        description: "Release value in stages rather than one big bang.",
      },
      {
        id: "delivery_review",
        label: "Request a delivery review",
        description: "Ask a Good Code specialist to pressure-test date versus scope.",
      },
    ],
  },
];

export const QUESTION_CATALOGUE: QuestionCatalogue = {
  version: "1.0.0",
  screens,
  questions,
  followUps,
};

export function getScreen(screenId: ScreenDefinition["id"]): ScreenDefinition | undefined {
  return screens.find((s) => s.id === screenId);
}

export function getQuestion(questionId: string): QuestionDefinition | FollowUpDefinition | undefined {
  return (
    questions.find((q) => q.id === questionId) ??
    followUps.find((q) => q.id === questionId)
  );
}

export function getQuestionsForScreen(screenId: ScreenDefinition["id"]): QuestionDefinition[] {
  return questions.filter((q) => q.screenId === screenId);
}

export function getVisibleFollowUps(
  answers: ProjectBlueprintAnswers,
  screenId?: ScreenDefinition["id"],
): FollowUpDefinition[] {
  return followUps.filter((f) => {
    if (screenId && f.screenId !== screenId) return false;
    return f.when(answers);
  });
}

export function getReviewScreenMeta(): ScreenDefinition {
  return screens.find((s) => s.id === "review")!;
}

export { screens as CATALOGUE_SCREENS, questions as CATALOGUE_QUESTIONS, followUps as CATALOGUE_FOLLOW_UPS };
