export const PASSWORD_MIN_LENGTH = 12;

export const AUTH_RATE_LIMIT_WINDOW_MS = 15 * 60 * 1000;
export const AUTH_RATE_LIMIT_MAX_HITS = 10;

export const LOGIN_LOCKOUT_MAX_ATTEMPTS = 5;
export const LOGIN_LOCKOUT_MS = AUTH_RATE_LIMIT_WINDOW_MS;
